// Downloads the site's webfonts from Google Fonts into public/fonts/ so the
// site never has to reach fonts.googleapis.com at runtime.
//
// WHY: fonts.googleapis.com / fonts.gstatic.com are unreachable from mainland
// China — our entire audience. A CSS `@import` to a blocked host is also
// render-blocking, so those users waited out a TCP timeout and *then* lost the
// brand face anyway. Self-hosting fixes both.
//
// This script only fetches the *latin* + *latin-ext* subsets: the site's own
// copy is zh/en, Chinese text renders from the system stack, and unicode-range
// means an unused subset is never downloaded by the browser.
//
// Run from repo root:  node scripts/fetch-fonts.mjs
// It rewrites public/fonts/*.woff2 and src/styles/fonts.css. Both are committed
// — this runs when the font list changes, not at build time.
import { mkdirSync, writeFileSync } from 'node:fs';

const OUT = 'public/fonts';
const CSS_OUT = 'src/styles/fonts.css';
const SPEC = 'family=Caprasimo:wght@400&family=Figtree:wght@400;600;700&family=JetBrains+Mono:wght@400;500;700';
// A modern desktop UA is required — Google serves woff2 only to browsers it
// recognises, and legacy UAs get ttf.
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';
const KEEP = new Set(['latin', 'latin-ext']);

const slug = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

const res = await fetch(`https://fonts.googleapis.com/css2?${SPEC}&display=swap`, {
  headers: { 'User-Agent': UA },
});
if (!res.ok) throw new Error(`Google Fonts CSS ${res.status}`);
const css = await res.text();

// The CSS is a flat list of `/* subset */` + @font-face pairs. Parse it rather
// than hand-listing URLs: the hashed gstatic filenames change on every release.
const faces = [];
const re = /\/\*\s*([\w-]+)\s*\*\/\s*@font-face\s*\{([^}]+)\}/g;
for (const [, subset, body] of css.matchAll(re)) {
  if (!KEEP.has(subset)) continue;
  const pick = (k) => (body.match(new RegExp(`${k}:\\s*([^;]+);`)) || [])[1]?.trim();
  faces.push({
    subset,
    family: pick('font-family').replace(/['"]/g, ''),
    weight: pick('font-weight'),
    style: pick('font-style'),
    range: pick('unicode-range'),
    url: body.match(/url\((https:[^)]+)\)/)[1],
  });
}
if (!faces.length) throw new Error('parsed 0 @font-face blocks — did the CSS format change?');

// Figtree and JetBrains Mono are variable fonts: Google points every requested
// weight at ONE file. Dedupe by URL so we store each file once.
mkdirSync(OUT, { recursive: true });
const fileFor = new Map();
for (const f of faces) {
  if (fileFor.has(f.url)) continue;
  const name = `${slug(f.family)}-${f.subset}.woff2`;
  const buf = Buffer.from(await (await fetch(f.url, { headers: { 'User-Agent': UA } })).arrayBuffer());
  writeFileSync(`${OUT}/${name}`, buf);
  fileFor.set(f.url, name);
  console.log(`  ${name}  ${(buf.length / 1024).toFixed(1)}KB`);
}

// Mirror Google's own per-weight declarations (a discrete `font-weight` on a
// variable file pins that axis — synthesising bold instead would be wrong).
const block = faces.map((f) => `@font-face {
  font-family: '${f.family}';
  font-style: ${f.style};
  font-weight: ${f.weight};
  font-display: swap;
  src: url('/fonts/${fileFor.get(f.url)}') format('woff2');
  unicode-range: ${f.range};
}`).join('\n');

writeFileSync(CSS_OUT, `/* GENERATED by scripts/fetch-fonts.mjs — do not edit by hand.
   Self-hosted webfaces (see the script header for why we don't use the Google
   Fonts CDN). global.css @imports this with a relative path, so Vite inlines it
   at build time — no extra request. unicode-range means a browser only fetches
   the subsets a page actually uses. */
${block}
`);

console.log(`\n${faces.length} faces / ${fileFor.size} files → ${CSS_OUT}`);
